### ISSUE TITLE
Question - Can chef-node follow redirects?

### ISSUE THREAD

**Issue by spuder** [sgentle/chef-node#16]
I'm trying to get this module up and running, and it works great for fetching data, however when I try and push data, I get the following error. 

``` xml
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty/1.7.10.1</center>
</body>
</html>
```

Here is my index.js

``` node
var express = require('express');
var router = express.Router();

router.post('/foobar', function(req,res) {
  var client = req.client;
  client.get('/nodes/foo',function(err,res,body){
    body.run_list.push('role[fooy]');
    client.post('/nodes/foo',body,function(err,res,body){
      console.log(err ? err : body);
    });
  });
});
```

Does this module natively follow 301 redirects? I've been trying to use this workaround with no luck. 
http://stackoverflow.com/a/13390241/1626687

Are there any other examples out there that show the proper way to post data? 

Express 4
Node 0.12.4
OSX

**Comment by mal** [comment]
I just tested the example in the readme against a Chef 11 server, the only significant thing I had to change aside from creds was the Chef address; to be https and not port 4000.

I don't see any relevant [API changes in 12](https://github.com/chef/opscode-omnibus/blob/master/RELEASE_NOTES.md#api-changes), but could you confirm which version of Chef Server you're running?

Also please try running your client get/post code in isolation.

**Comment by spuder** [comment]
Thanks for responding. I"m just learning node, so I'm not sure on the proper way to run a client get/post in isolation. 

I'm running the latest chef 12. I do have to change the URL from `chef.example.com:443` to `chef.example.com:443/organizations/foo`

I've been playing around more and I think I figured it out. Sharing for posterity. 

``` node
var fs = require('fs'),
    chef = require('chef'),
    key = fs.readFileSync('/Users/sowen/.chef/spuder.pem'),
    client = chef.createClient('spuder', key, 'https://chef.example.com:443/organizations/lab');

var abody = { "name": "herp","default_attributes": {},"json_class": "Chef::Environment","description": "","cookbook_versions": {},"chef_type": "environment"}

client.post('/environments', abody, function(err, res, body) {
    if (err) {return console.log(err);}
    console.log(body);
});
```

Here is another example that will update a databag item "breakfast/food/sausage"

``` node
var foo = client.get('/data/breakfast/food', function(err,res,body) {
  if (err) {return console.logl(err);}
  console.log(body)
});

var sausage = { "id":"food","sausage":"good"}
client.put('/data/breakfast/food', sausage,  function(err,res,body) {
  if (err) { return console.log(err); }
  console.log(body)
});

```

**Comment by spuder** [comment]
Turns out that you can do GET from a http address, but you can only do POST and PUT to a https address in chef 12

Making sure that I use https:// fixed the 301 errors.
